class Autogenerated {
  int? empid;
  String? empname;
  String? emploc;

  Autogenerated({this.empid, this.empname, this.emploc});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    empid = json['empid'];
    empname = json['empname'];
    emploc = json['emploc'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['empid'] = this.empid;
    data['empname'] = this.empname;
    data['emploc'] = this.emploc;
    return data;
  }
}